# This is a basic workflow to help you get started with Actions

name: My-GitHub-Action-Basics
env:
  APLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deploy_ver_${{ github.sha }}"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
        - main
 
jobs:
  # This workflow contains a single job called "build"
    my_testing:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

      steps:
      - name: Print Hello Massage
        run : echo "Hello World from testing"

      - name: Execute few commands
        run: |
           echo "Hello Mesage1"
           echo "Hello Message2"
           echo "Application name: ${{ env.APLICATION_NAME }}"
    my_deploy:
       runs-on: ubuntu-latest
       needs: [my_testing]
       
       steps:
       - name: Print Hello Massage
         run : echo "Hello World from deploy"

       - name: Deployment package Print
         run:
           echo "Deploq package name is ${{ env.PACKAGE_NAME }}"
